name: "godot-tester"
description: "Runs all GUT tests you have for your Godot game"
inputs:
  version:
    description: "Your Godot version number e.g. 3.2.2"
    required: true
    default: "3.2.2"
  release_type:
    description: "Your Godot release type e.g. rc2, beta3"
    required: false
    default: "stable"
  path:
    description: "Give relative path to your project.godot, if not in top level of repo"
    required: false
    default: "./"
  is-mono:
    description: "Test against mono version? Default: false"
    required: false
    default: "false"
  import-time:
    description: "How long to spend on importing assets, don't set if testing is not required"
    required: false
    default: "1"
  test-timeout:
    description: "How long the test should be run before it's timed out and fails"
    required: false
    default: "300"
  direct-scene:
    description: "If instead of running the GUT command line you'd like to run a GUT scene instead: recommended to extend gut's plugin script and exit godot when all tests complete"
    required: false
    default: "false"
  ignore-errors:
    description: "Disable Godot 'SCRIPT ERROR's from causing tests to fail"
    required: false
    default: "false"
  config-file:
    description: "Full path to your GUT config file, e.g. 'res://<path>/<config>.json'."
    required: false
    default: "res://.gutconfig.json"

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.version }}
  - ${{ inputs.release_type }}
  - ${{ inputs.path }}
  - ${{ inputs.is-mono }}
  - ${{ inputs.import-time }}
  - ${{ inputs.test-timeout }}
  - ${{ inputs.direct-scene }}
  - ${{ inputs.ignore-errors }}
  - ${{ inputs.config-file }}

branding:
  icon: 'chevron-right'
  color: 'green'
