name: "godot-tester"
description: "Runs all GUT tests you have for your Godot game"
inputs:
  version:
    description: "Your Godot version number e.g. 3.2.2"
    required: true
    default: "3.2.2"
  path:
    description: "Give relative path to your project.godot, if not in top level of repo"
    required: false
    default: "./"
  is-mono:
    description: "Test against mono version? Default: false"
    required: false
    default: "false"
  import-time:
    description: "How long to spend on importing assets, don't set if testing is not required"
    required: false
    default: "0"

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.version }}
  - ${{ inputs.path }}
  - ${{ inputs.is-mono }}
  - ${{ inputs.import-time }}

branding:
  icon: 'chevron-right'  
  color: 'green'
